name: dynamic_theme
description: Changes the theme during runtime, also presists brightness settings
  across restarts
version: 3.0.0
homepage: "https://github.com/TesteurManiak/dynamic_theme"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
